version: '3.9'
services:
  user_service:
    image: uweeds/user_service1:latest
    build:
      context: ./user-service
    ports:
      - "3001:3001"
    networks:
      - my_network
     

  product_service:
    image: uweeds/product_service1:latest
    build:
      context: ./product-service
    ports:
      - "3002:3002"
    networks:
      - my_network
      

  order_service:
    image: uweeds/order_service1:latest
    build:
      context: ./order-service
    ports:
      - "3003:3003"
    networks:
      - my_network
   
  nginx:
    image: uweeds/my_nginx:latest
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - my_network

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - my_network

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - my_network

networks:
  my_network:
